#
#  Copyright 2017-2022 Davide Bettio <davide@uninstall.it>
#
#  SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later
#

name: Build with Zephyr #todo: and test

on:
  push:
    paths:
      - '.github/workflows/build-and-test-zephyr.yaml'
      - 'src/platforms/zephyr/**'
      - 'src/libAtomVM/**'
  pull_request:
    paths:
      - '.github/workflows/stm32-build.yaml'
      - 'src/platforms/zephyr/**'
      - 'src/libAtomVM/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref != 'refs/heads/master' && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:

      fail-fast: false

      matrix:
        ports: [
          "native_sim_64",
          "qemu_x86_64",
          "blackpill_f411ce",
          "nucleo_f429zi",
          "stm32f4_disco"
        ]

    steps:
    - name: "Install apt deps"
      run: |
            sudo apt update -y
            sudo apt install -y cmake gperf zlib1g-dev doxygen valgrind libmbedtls-dev git ninja-build ccache dfu-util \
            device-tree-compiler wget python3-dev python3-pip python3-setuptools python3-venv python3-tk python3-wheel \
            xz-utils file make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1

    - uses: actions/cache@v3
      id: build-deps-cache
      with:
        path: |
              /home/runner/zephyrproject
              /home/runner/.local
              /home/runner/.cmake
        key: ${{ runner.os }}-build-deps

    - name: "Install West"
      if: ${{ steps.build-deps-cache.outputs.cache-hit != 'true' }}
      working-directory: /home/runner
      run: |
        mkdir zephyrproject
        python3 -m venv ~/zephyrproject/.venv
        source zephyrproject/.venv/bin/activate
        pip install west
        west init ./zephyrproject
        cd zephyrproject
        west update
        west zephyr-export
        pip install -r ./zephyr/scripts/requirements.txt

    - name: "Install Zephyr SDK"
      if: ${{ steps.build-deps-cache.outputs.cache-hit != 'true' }}
      working-directory: ${{ runner.temp }}
      run: |
        wget -q https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.4/zephyr-sdk-0.16.4_linux-x86_64.tar.xz
        wget -q -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.4/sha256.sum | shasum --check --ignore-missing
        cd /home/runner/.local
        tar xf ${{ runner.temp }}/zephyr-sdk-0.16.4_linux-x86_64.tar.xz
        cd /home/runner/.local/zephyr-sdk-0.16.4
        ./setup.sh -t all -h -c

    - uses: erlef/setup-beam@v1
      with:
        otp-version: master
        elixir-version: master

    - name: "Checkout repo"
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: "Build targets"
      working-directory: src/platforms/zephyr
      run: |
        source /home/runner/zephyrproject/.venv/bin/activate
        export ZEPHYR_BASE=/home/runner/zephyrproject/zephyr
        export ZEPHYR_SDK_INSTALL_DIR=/home/runner/.local/zephyr-sdk-0.16.4
        west build -b ${{ matrix.ports }} -p=auto .

    ## TODO: Add tests for native_sim_64 and qemu_x86_64
